### ISSUE TITLE
Select Input and Multiselect Input are not binding to state

### ISSUE THREAD

**Issue by hragbalian** [streamsync-cloud/streamsync#102]
When I try to bind a dictionary within the state to either a Select Input or Multiselect Input, I'm not seeing any evidence of any binding.  The default value of {"a": "Option A", "b": "Option B"} persists.

**Comment by ramedina86** [comment]
Hi, I developed several apps this week using that feature, across Linux, Win and Mac, so I'm confident the feature in general works. However, there might be something else at play?

This is simple example:

<img width="866" alt="Screenshot 2023-09-09 at 09 47 53" src="https://github.com/streamsync-cloud/streamsync/assets/64783088/45cb00b8-13c3-4a05-bd03-4dec096ba8e0">

**Comment by hragbalian** [comment]
Ok, thanks @ramedina86, must've been user error. Sorry about that.

**Comment by ramedina86** [comment]
No worries! Thanks for trying Streamsync
