### ISSUE TITLE
Add bolding of text in DataFrame. Or have each cell interpret "\n" characters to break lines.

### ISSUE THREAD

**Issue by samgarvis** [streamsync-cloud/streamsync#103]
We have an issue where we need to highlight certain text in a cell. This can be achieved by either allowing bolding of certain text in a cell. Or, ideally, have each cell read the "\n" character for a new line. So if in the DataFrame, a cell contained "hello\nmy\nname\nis\nsame", there would be 5 lines in the cell, and it would automatically expand the size of the cell. This would be a HUGE performance increase for us. Being able to bold specific words would be great also.

We love your product, and think this is the best UI for Python out there.
Thank you so much

**Comment by ramedina86** [comment]
Hi, the line break fix in _DataFrame_ is available in v0.2.7.

Please note two things:
- To display the line break, it'll need to be in wrap text mode.
- Pandas by itself doesn't process `\n` as a new line when opening a CSV, so you may need something like
```py
 main_df["eye_color"] = main_df["eye_color"].str.replace("\\n", "\n")
```
to turn the `\n` into an actual line break in the dataframe.

The format field will be part of a future update, likely before the end of month. Thanks for your input!
