### ISSUE TITLE
Multiselect input bug

### ISSUE THREAD

**Issue by versus666jzx** [streamsync-cloud/streamsync#106]
Multiselect dropdown menu doesn't collapse after user finished input and clicked in some page area.

![image](https://github.com/streamsync-cloud/streamsync/assets/49030147/d74c2907-ee93-493c-bf31-e1a5fc008e55)

Streamsync version - 0.2.6
Tested on Chrome, Firefox and MS Edge browsers.

**Comment by ramedina86** [comment]
Hi, thanks for reporting. This focus issue has already been fixed and will be deployed in the next release during the next couple of days.

**Comment by ramedina86** [comment]
Fixed in v0.2.7, thanks again for reporting.
