### ISSUE TITLE
Blocked on browser loading screen

### ISSUE THREAD

**Issue by cdromain** [streamsync-cloud/streamsync#108]
Hey guys,

Discovered Streamsync recently and was excited to give it a try, but I can't get the `streamsync hello` demo, or any app (either run or edit) to actually show up in my browser - I'm stuck on the loading page :

![image](https://github.com/streamsync-cloud/streamsync/assets/9213738/91282e0d-2d3a-4b8e-a840-4af61e23c0b9)

I installed the streamsync package as mentioned in the doc in a dedicated conda environment (`conda create -n streamsync python>=3.9.2 pip` and then `pip install "streamsync[ds]"`) and tried everything I could think of. Localhost, different ports... Actually using same parameters as with Streamlit so this does not seem to be the problem.
Is there a problem with running Streamsync within an Anaconda env ?

The [web demo](https://hello.streamsync.cloud/) does work without issue.

From Chrome's DevTools I could see the following error :
```Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.```

### Specs
- Windows 10 Pro
- Anaconda 64bits
- Streamsync last version (0.2.6)
- Tried with different versions of Python >= 3.9.2 as recommended in the docs
- Tried with Chrome and Edge browsers

### Output of `conda list` 
Name                    Version                   Build  Channel
annotated-types           0.5.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
ca-certificates           2023.08.22           haa95532_0
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
fastapi                   0.103.1                  pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
numpy                     1.25.2                   pypi_0    pypi
openssl                   1.1.1w               h2bbff1b_0
packaging                 23.1                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pip                       23.2.1           py39haa95532_0
plotly                    5.16.1                   pypi_0    pypi
plotly-express            0.4.1                    pypi_0    pypi
pyarrow                   12.0.1                   pypi_0    pypi
pydantic                  2.3.0                    pypi_0    pypi
pydantic-core             2.6.3                    pypi_0    pypi
python                    3.9.2                h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
setuptools                68.0.0           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
starlette                 0.27.0                   pypi_0    pypi
statsmodels               0.14.0                   pypi_0    pypi
streamsync                0.2.6                    pypi_0    pypi
tenacity                  8.2.3                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
uvicorn                   0.23.2                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.3.1                    pypi_0    pypi
websockets                10.4                     pypi_0    pypi
wheel                     0.38.4           py39haa95532_0

Thanks and all the best,

Romain

**Comment by PasVegan** [comment]
I often get that too, I just close the page and try to open it like 10 seconds later. If that doesn't work, I close the page and relaunch the app. Hope that helps you :)

**Comment by cdromain** [comment]
Thanks for your reply Quentin but I've tried that and still can't get past the loading animation. Tried everything I could think of to have the `streamsync hello` demo show up in my Chrome browser, but to no avail.

**Comment by cdromain** [comment]
Thanks for your reply Quentin but I've tried that and still can't get past the loading animation. Tried everything I could think of to have the `streamsync hello` demo show up in my Chrome browser, but to no avail.

**Comment by SurajRaika** [comment]
May be WebSocket is not able to connect...
try 
running it in port 5000
```shell
streamsync edit testapp --port 5000
```

**Comment by cdromain** [comment]
Thanks @SurajRaika, had already tried different ports using the dedicated `--port` argument.
But your suggestion made me think - maybe there is something (a port ?) that would be closed on my work laptop ? (I'm running Streamsync from whithin the company environment)
Streamlit does not have that issue though.
Will try and dig more but I'd appreciate some feedbacl from the Streamsync team. @ramedina86 What should be open that Streamlit does not need ?
Thanks all ! Hopefully this could be useful to others starting out as well.

**Comment by PasVegan** [comment]
Maybe it's windows firewall blocking things ?

**Comment by cdromain** [comment]
Thanks Quentin but what I want to know is what is getting blocked during this loading stage, so I could (hopefully) get it unblocked by our IT - but for that I do need more info.
What I know is that I don't have any issue with Streamlit loading up in my browser.

**Comment by ramedina86** [comment]
Hello @cdromain thanks for your interest in trying Streamsync, it's appreciated.

Several users work with Anaconda on Windows, in fact I work daily with some of them, and they don't experience any issues.

I assume it's another aspect of your environment. There should be communications to a single port via HTTP and WebSockets, nothing else should be open. This is similar to Streamlit's requirement so I don't think it's a networking issue.

What hasn't been tested is Windows 10, I'll spin up a VM and see if I can reproduce the issue.

**Comment by PasVegan** [comment]
Did you try on another computer within your company environment ?

**Comment by cdromain** [comment]
Hey Quentin, no not yet but I doubt the results would be any different, as our configurations are quite normalized. Thanks

**Comment by cdromain** [comment]
Hey guys, we tried on another computer today (Win 10 as well) and `streamsync hello` worked. It made me realize that @ramedina86 released an updated v.0.2.7 five days ago (I was running 0.2.6).

Unfortunately Streamsync v0.2.7 still does not work on my laptop (tested in a fresh environment). We're trying to think about differences between both computers that could lead us to a solution but there are very few.

**Comment by FabienArcellier** [comment]
Hi,

Could you run the following snippet in python ?

```python
import mimetypes

mimetypes.guess_type('hey.js')
```

Second, did you try this solution ? (https://stackoverflow.com/a/64638286/2141982)

**Comment by cdromain** [comment]
Hey @FabienArcellier,

Thanks so much for your input, problem solved 😀

`mimetypes.guess_type('hey.js')` returned `('text/plain', None)`, which is coherent with Chrome's DevTools error I mentioned above.
The Django SO solution worked : changed `HKEY_CLASSES_ROOT\.js\Content Type` to `text/javascript` (was `text/plain`) using Windows RegEdit, then rebooted and cleared Chrome cache - `streamsync hello` now loads correctly in Chrome !
Closing the issue.

Thanks again for your help, cheers

**Comment by FabienArcellier** [comment]
@ramedina86 We may add the detection of mimetype if the command `mimetypes.guess_type('hey.js')` return the wrong input. It may avoid to explain the trick to user that has the issue.

The pattern is use frequenty : https://github.com/search?q=mimetypes.add_type&type=code

I'm not sure of the impacts.
