### ISSUE TITLE
Q: How to set the checkboxes from the backend

### ISSUE THREAD

**Issue by thondeboer** [streamsync-cloud/streamsync#121]
May not be possible ATM, but how could I set the value of a checkbox to be selected from the backend?
I have a long list and need a "Select all" option so the user does not have to click all the boxes and can deselect the ones that need to be removed.

**Comment by thondeboer** [comment]
Also, seems checkboxex cannot be part of a horizontal stack? It places them above or below the existing stach

**Comment by PasVegan** [comment]
can't you use a state binding for your checkbox and set it with a dictionary containing every keys/values to select everything ?

**Comment by thondeboer** [comment]
User error. Setting the selection to a list of value checks the marks from the backend
