### ISSUE TITLE
[QUESTION] is it possible to mount the streamsync app into an existing frontend application?

### ISSUE THREAD

**Issue by gryphonmyers** [streamsync-cloud/streamsync#126]
I am wondering if it would be possible to build the streamsync frontend (which I understand to be a vue component) and import it into another application. I read through the docs, but I'm not quite clear on if I should expect to be able to do this. Is it possible? If so, is there any reason the app couldn't be built as a [web component](https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue)? Use case is, we have an existing React application that we would want to render streamsync into.

**Comment by ramedina86** [comment]
Hi, Streamsync is a rather complex framework that spans backend and frontend, similarly to Streamlit. You also need its backend server at all times, with support for websockets. There's no way to use it as a web component.

You could embed Streamsync (or other frameworks such as Streamlit) using an iframe an ensuring to mount the backend server. What I do in my day job is deploy Streamsync applications in Docker containers which I later embed in iframes. There are no water marks (unlike Streamlit) so aesthetically it works well, but it's a completely independent app, which doesn't seem to be what you're after.
