### ISSUE TITLE
When page has two or more dataframes, resizing one dataframe, rezies all dataframe columns

### ISSUE THREAD

**Issue by thondeboer** [streamsync-cloud/streamsync#136]
I have two dataframes on a page (inside a repeater and tabs) and when you resize one dataframes's columns, you resize them all.

**Comment by ramedina86** [comment]
Thank you very much for reporting this. I was able to reproduce it and I've fixed it; the fix will be deployed with the next version.

**Comment by ramedina86** [comment]
This was fixed earlier, but forgot to close the issue. Thanks again for reporting it!
