### ISSUE TITLE
Streamsync sometimes gets stuck. Possibly in a deadlock

### ISSUE THREAD

**Issue by aleloi** [streamsync-cloud/streamsync#185]
I have experienced the streamsync server to become unresponsive a few times. It doesn't finish setting up new connections, but I do see the green+white rectangle loading screen (screeshot attached). It also ignores keyboard interrupt signals. It stops responding to source file changes. What I did in these scenarios is `kill -9 $STREMSYNC_PID`. Here is what the main thread was doing when it was killed:

```
(streamsync) alex@alex-thinkpad:~/streamsync$ (streamsync) alex@alex-thinkpad:~/streamsync$ (streamsync) alex@alex-thinkpad:~/streamsync$ {"log_level": "ERROR",  "time": "2023-12-19 12:16:15,972", "function": "_invoke_callbacks",  "message": "exception calling callback for <Future at 0x7f7fae8cd3d0 state=finished returned tuple>"}
Traceback (most recent call last):
  File "/home/alex/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/alex/.pyenv/versions/3.11.6/envs/streamsync/lib/python3.11/site-packages/streamsync/app_runner.py", line 370, in _send_packet
    self.server_conn.send(result)
  File "/home/alex/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/alex/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/connection.py", line 421, in _send_bytes
    self._send(buf)
  File "/home/alex/.pyenv/versions/3.11.6/lib/python3.11/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
  C-c C-c
```

I should note that I have only witnessed this happening in `edit`-mode, and (I think) only after I save files that I'm editing. I have configured my editor to save files every few seconds, and maybe something in streamsync can't keep up with the constant re-loading?

Does anyone have suggestions for how do debug this further the next time it happens? I don't have a reliable way to reproduce and I have no ideas except adding more logging to streamsync itself.

![2023-12-19-141941_886x562_scrot](https://github.com/streamsync-cloud/streamsync/assets/16827347/997b455a-ea61-4f01-aac1-aa08fcad5292)

**Comment by FabienArcellier** [comment]
It would be a huge help if you could make an export of `lsof -p <pid>` when it happen. It will show us the opened files & socket at this time. (feel free to filter part you don't want to share with us)

**Comment by aleloi** [comment]
Hi, sorry for not getting back about this. Attached are two `lsof -p $PID` commands for the two streamsync processes when one gets stuck. I couldn't infer why it's stuck based on the lsof output because the processes use the same resources when running normally.
[streamsync_lsof_list.log](https://github.com/streamsync-cloud/streamsync/files/13960586/streamsync_lsof_list.log)

**Comment by FabienArcellier** [comment]
@aleloi I have failed reproducing this issue using 3.11.7. I would have a few questions to continue looking at it :

* Does it happen on hello application ? Does it happen only on your own application ?
* Could you share an application that trigger the error on your machine ?
* What is your configuration (OS, streamsync version) ?

**Comment by FabienArcellier** [comment]
I reproduce something similar using a script that reproduce the behavior of an IDE that would save file every 0.5 seconds. What is your IDE and what is your save frequency ?

```python
import io
import time

while(True):
    with io.open("apps/hello/main.py", 'a') as filep:
        filep.write('##')
        time.sleep(0.5)
```

**Comment by FabienArcellier** [comment]
I'm closing this issue. If you still encounter this problem, you should reopen it by sharing updated information on the situation. Thanks
