### ISSUE TITLE
Error when assign state to Dropdown Input, Select Input and Multiselect Input

### ISSUE THREAD

**Issue by duckunz** [streamsync-cloud/streamsync#187]
I have created 1 state named var1 = [111,222,333] and tried to assign to Radio Input, Checkbox Input, Dropdown Input, Select Input and Multiselect Input, but only Radio Input, Checkbox Input works.

The other 3 does not get any changes. Can you help me please
![variable](https://github.com/streamsync-cloud/streamsync/assets/142195300/37e75004-1cae-4137-986b-d76b1334c1bc)
![Radio Input](https://github.com/streamsync-cloud/streamsync/assets/142195300/e2ee20d5-d811-4320-bb45-99d3cf6eaabe) 
![Multiselect input nothing happened](https://github.com/streamsync-cloud/streamsync/assets/142195300/7c4ac94f-1160-48d7-8745-10e51ca0d49e)

**Comment by FabienArcellier** [comment]
You have to use dictionary as options on components. It constrains you to use text value, not numeric.
```python
{
  "111": "111",
  "222": "222",
  "333": "333"
}
```

**Comment by thondeboer** [comment]
And the payload of a selected multiselect item will be a list of your KEYS from your dict, so you CAN set the values of your multi-select as the default to make your multiselect item BOUND to "var1" but the definition of the multiselect needs to be a dict with the way Fabien indicated...

**Comment by duckunz** [comment]
Thanks for your help. Another question for Radio Input. I have chosen binding of the Radio Input to input1 state like this image below
![before](https://github.com/streamsync-cloud/streamsync/assets/142195300/28cb238e-420c-40f6-822f-c32eb67e9c0e)
but when I choose 1 option I get an error
![after](https://github.com/streamsync-cloud/streamsync/assets/142195300/fd0caab2-e6e7-4504-b799-172b7abab2a4)

And also can you please give me the tutorial on how to select input1 (Radio Input, Multiselect input) and then change another state (e.g state2) based on the selected input1

Thanks in advance

**Comment by thondeboer** [comment]
https://www.streamsync.cloud/getting-started.html

But you should also provide your code in these cases, since it is not clear what you are trying to do.

I suggest you start simple and just look at the PAYLOAD of any of the components when you use a handler so you can see what they output when selected. Binding it to a state variable is then the next step. You usually design a handler to deal with the payload and there you make your logic what to do with the output, like setting the state of another variable etc.

Here's some quick code to get you started . Paste it into the files (ui.json you need to do outside the webpage).

This just connects each of the components in the UI to the handler `show_payload` which will simply display what it received from the component. Then you design a new handler for each component and put the logic to decide what do do with the component in that handler. any changes to `state` variable will be reflected in the UI (if they are connected to the component, either with th e@{} notation or bound in the binding section on the UI, with just the state name ("var1" not "@{var1}" in those cases

```python
import streamsync as ss
import json

# Shows in the log when the app starts
print("Started app")


initial_state = ss.init_state({
    "message": "Payload will appear here..."
})

def show_payload(state, payload, context):
    state['message'] = json.dumps(payload)

```

ui.json
```json
{
    "metadata": {
        "streamsync_version": "0.2.8"
    },
    "components": {
        "root": {
            "id": "root",
            "type": "root",
            "content": {
                "appName": "My App"
            },
            "parentId": null,
            "position": 0,
            "handlers": {},
            "visible": true
        },
        "c0f99a9e-5004-4e75-a6c6-36f17490b134": {
            "id": "c0f99a9e-5004-4e75-a6c6-36f17490b134",
            "type": "page",
            "content": {
                "pageMode": "compact"
            },
            "parentId": "root",
            "position": 0,
            "handlers": {},
            "visible": true
        },
        "faad46c9-2344-4cf1-a74d-e586ea83fbfa": {
            "id": "faad46c9-2344-4cf1-a74d-e586ea83fbfa",
            "type": "textareainput",
            "content": {
                "label": "Log message",
                "placeholder": "@{message}",
                "rows": "20"
            },
            "parentId": "c0f99a9e-5004-4e75-a6c6-36f17490b134",
            "position": 3,
            "handlers": {},
            "binding": {
                "eventType": "ss-change",
                "stateRef": "message"
            },
            "visible": true
        },
        "mflpw3julpq46khc": {
            "id": "mflpw3julpq46khc",
            "type": "radioinput",
            "content": {
                "label": "Input Label"
            },
            "parentId": "c0f99a9e-5004-4e75-a6c6-36f17490b134",
            "position": 0,
            "handlers": {
                "ss-option-change": "show_payload"
            },
            "binding": {
                "eventType": "ss-option-change",
                "stateRef": "radio_selected"
            },
            "visible": true
        },
        "tf1cqlkwfwu3r9nl": {
            "id": "tf1cqlkwfwu3r9nl",
            "type": "button",
            "content": {
                "text": "Button Text"
            },
            "parentId": "c0f99a9e-5004-4e75-a6c6-36f17490b134",
            "position": 2,
            "handlers": {
                "ss-click": "show_payload"
            },
            "visible": true
        },
        "aljeqyh26vczfg3r": {
            "id": "aljeqyh26vczfg3r",
            "type": "multiselectinput",
            "content": {
                "label": "Input Label"
            },
            "parentId": "c0f99a9e-5004-4e75-a6c6-36f17490b134",
            "position": 1,
            "handlers": {
                "ss-options-change": "show_payload"
            },
            "visible": true
        }
    }
}
```
Hope this gets you started...It's a great platform so worth getting to know.

**Comment by duckunz** [comment]
Thanks for your instruction, but in my case  I want to do the logic as follows

1. create a Select Input (or Multiselect Input) with 2 options: "High" and "Low" to represent stock price and apply this logic
1.1. if I choose "High", the page will show a radio input with 2 options: "Buy" and "Keep"
1.2. if I choose "Low" , the page will show a radio input with 2 options:  "Sell" and "Keep"
2. The selection of Select Input will be stored in variable (or state) named var1
3. Then I will choose the Radio Input. The selection of radio Input will be stored in variable (or state) named var2
4. create and create a button. if I click this button and the selection, a message will appear. For example, I choose Buy and click, a message will appear as "You have sold this stock"

Please help me to create a demo video and code for all this logic because I'm quite new to Python and also Streamsync.

**Comment by ramedina86** [comment]
Hi, as @thondeboer and @FabienArcellier were explaining, this seems to be a matter of getting more familiar with the syntax and flow rather than a bug, hence closing the issue.
