### ISSUE TITLE
Invalid escape sequence in core.py

### ISSUE THREAD

**Issue by ramedina86** [streamsync-cloud/streamsync#216]
Currently line 237 of `core.py` reads:

`escaped_key = key.replace(".", "\.")`

This syntax has been deprecated and Python 3.12 throws a `SyntaxWarning`. I believe the `\.` should be replaced to `\\.` to properly escape the backslash.

Relevant resource: https://stackoverflow.com/questions/77531208/python3-12-syntaxwarning-on-triplequoted-string-d-must-be-d

**Comment by ramedina86** [comment]
Hey @mmikita95 since you're working around these lines, can you please fix this small issue? Thanks

**Comment by mmikita95** [comment]
@ramedina86 A simple fix – decided to get it off the table today to keep things less cluttered in our issue list. A [PR](https://github.com/streamsync-cloud/streamsync/pull/232) is ready for review.

**Comment by mmikita95** [comment]
[Merged successfully](https://github.com/streamsync-cloud/streamsync/pull/232).
