### ISSUE TITLE
 streamsync 0.3.0 installation problem on Windows11

### ISSUE THREAD

**Issue by SergeyPriem** [streamsync-cloud/streamsync#218]
**_During the installation of streamsync 0.3.0 I got the error:_**

UPDATING build\lib.win-amd64-cpython-312\pandas/_version.py
      set build\lib.win-amd64-cpython-312\pandas/_version.py to '1.5.3'
      running build_ext
      building 'pandas._libs.algos' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pandas
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [286 lines of output]
      <string>:34: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'

**_After installing "Microsoft C++ Build Tools" the error is still there_**

**_At the end of installation, I got one more message:_**

      running build_ext
      creating C:\Users\sprie\AppData\Local\Temp\pip-install-znlbpykz\pyarrow_10dca4d27d744760a0f42fff7dbb18df\build\temp.win-amd64-cpython-312
      -- Running cmake for PyArrow
      cmake -DCMAKE_INSTALL_PREFIX=C:\Users\sprie\AppData\Local\Temp\pip-install-znlbpykz\pyarrow_10dca4d27d744760a0f42fff7dbb18df\build\lib.win-amd64-cpython-312\pyarrow -DPYTHON
_EXECUTABLE=C:\0_D\sync\.venv\Scripts\python.exe -DPython3_EXECUTABLE=C:\0_D\sync\.venv\Scripts\python.exe -DPYARROW_CXXFLAGS= -G "Visual Studio 15 2017 Win64" -DPYARROW_BUILD_CUD
A=off -DPYARROW_BUILD_SUBSTRAIT=off -DPYARROW_BUILD_FLIGHT=off -DPYARROW_BUILD_GANDIVA=off -DPYARROW_BUILD_ACERO=off -DPYARROW_BUILD_DATASET=off -DPYARROW_BUILD_ORC=off -DPYARROW_
BUILD_PARQUET=off -DPYARROW_BUILD_PARQUET_ENCRYPTION=off -DPYARROW_BUILD_GCS=off -DPYARROW_BUILD_S3=off -DPYARROW_BUILD_HDFS=off -DPYARROW_BUNDLE_ARROW_CPP=off -DPYARROW_BUNDLE_CYTHON_CPP=off -DPYARROW_GENERATE_COVERAGE=off -DCMAKE_BUILD_TYPE=release C:\Users\sprie\AppData\Local\Temp\pip-install-znlbpykz\pyarrow_10dca4d27d744760a0f42fff7dbb18df
      error: command 'cmake' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyarrow
Failed to build pandas pyarrow
ERROR: Could not build wheels for pandas, pyarrow, which is required to install pyproject.toml-based projects

**_Windows 11 Home (23H2), Python 3.12, PyCharm 2023.3.3_**

**_Please, advise, how to fix?_**

**Comment by ramedina86** [comment]
Hey Sergey! Good to see you here.

It seems like the pyarrow version included in `streamsync[ds]` isn't compatible with Python 3.12 (it doesn't have wheels for this version).

I recommend doing:
`pip install streamsync`
`pip install pandas plotly-express pyarrow`

Of course, this is a temporary fix and we'll upgrade the dependencies for the next version. Thanks for reporting this.

**Comment by SergeyPriem** [comment]
Hello, Ramiro!

Glad to hear from you!

Thank you for the fast response and for the continuous development of the Framework!!!

Best wishes!

________________________________

**Comment by mmikita95** [comment]
As I've mentioned in our discussion of [#227](https://github.com/streamsync-cloud/streamsync/issues/227#issuecomment-1933651692), I've had quite a similar issue with pyarrow on macOS (I went a little bit further digging around it though, with `xcode-select --install` and installing `cmake` and `apache-arrow` through Homebrew, which ultimately didn't help). [Fabien's poetry setup](https://github.com/streamsync-cloud/streamsync/pull/231) is essentially what allowed me to bypass it – installing a newer version of pyarrow along the way. Just wanted to add it here as well as it's relevant to this issue as I believe.

**Comment by ramedina86** [comment]
Dependencies were updated and this should no longer be an issue in 0.4.0.
