### ISSUE TITLE
change on value of a graph as vega spec does not trigger mutation in extension

### ISSUE THREAD

**Issue by FabienArcellier** [streamsync-cloud/streamsync#226]
When a change is performed inside a data structure, it doesn't trigger mutation or it trigger mutation unproperly. (view [discord link](https://discord.com/channels/1154359809454379088/1154359809454379091/1201736878487769178))

```python
def plotly_test_ten(state):
    state["plotly_spec"]["data"][0]["y"][0] = 10
```

```python
initial_state = ss.init_state({
    "chart_spec": {
        "$schema": "../vega-lite-schema.json",
        "description": "A simple bar chart with embedded data.",
        "width": 1000,
        "data": {
            "values": [
                {"time": 1000, "value": 90},
                {"time": 2000, "value": 11},
                {"time": 3000, "value": 12},
            ]
        },
        "mark": "point",
        "encoding": {
            "x": {"field": "time", "type": "quantitative", "title": "Time (milliseconds)"},
            "y": {"field": "value", "type": "quantitative", "title": "Value"}
        }
    }
})
```

### Proposal

**it looks like a wrong idea**

I would propose to implement a `StateObjectProxy` to handle this usecase. It will allow to perform check and identify if a mutation has happen on it or on any of it's children. If mutation has happen on it, it will raise the mutation at the level of the declaration. On the example below, it would be "chartspec".

We would need other internal object to manage List and maybe tuple (not sure it's necessary).

```python
initial_state = ss.init_state({
    "chart_spec": ss.state_object({
        "$schema": "../vega-lite-schema.json",
        "description": "A simple bar chart with embedded data.",
        "width": 1000,
        "data": {
            "values": [
                {"time": 1000, "value": 90},
                {"time": 2000, "value": 11},
                {"time": 3000, "value": 12},
            ]
        },
        "mark": "point",
        "encoding": {
            "x": {"field": "time", "type": "quantitative", "title": "Time (milliseconds)"},
            "y": {"field": "value", "type": "quantitative", "title": "Value"}
        }
    })
})
```

What do you think about it ?

**Comment by ramedina86** [comment]
Not a bug, [documented here](https://www.streamsync.cloud/event-handlers.html#mutation-detection).

Unless there's a very efficient way that I don't know of, I'd argue against this.

**Comment by FabienArcellier** [comment]
I agree with you. So 

On this specific case, it does not work because the "chart_spec.data" is handle as StateProxy where to work here, it should be handle as a classic dict.

Naively, I would propose to modify sligthly the method `get_mutations_as_dict` to handle the case where the field has been mutated first. I am not sure about the consequence or I would added a method ``mutate`` on StateProxy to call ``state["plotly_spec"].mutate()``.

```python
            if key in self.mutated:
                ...
            elif isinstance(value, StateProxy):
                ...
```

**Comment by ramedina86** [comment]
Apologies for removing the "bug" label then 😄 

Let's park this for a few days until @mmikita95 is done with his async handlers work and you can work on this together. He's been doing some great work on state and as I told him earlier, he now understands it better than I do.

**Comment by mmikita95** [comment]
@ramedina86 – thanks a lot, I'm very honored to hear that from you!

Regarding the issue at hand, this is something I was thinking about myself, and quite in a similar direction – it appears that for "complex" children of `StateProxy` (lists, dicts, instances of classes, etc.) we might require some sort of a wrapper-handler class to properly control and report mutations "upwards" to the `StateProxy`. Though, this seems it might introduce a lot of potential overhead, which wouldn't be ideal. But yeah, as for me, I'm struggling to think of something more reliable in this case.

As Ramiro said, I'll be wrapping up my work on async handlers and will gladly join to work on this.

**Comment by FabienArcellier** [comment]
I have check an hypothesis about the impact of using an implem based on list and an implem based on Collection with dunded method. I am surprised on how similar byte code is. I have to perform a real impact on performance on massive list. 

here is the byte code difference : https://www.diffchecker.com/jWNSGfMp/

```python
def func():
    a = [1, 2, 4]
    for elt in a:
        print(elt)

    a[1] = 53
    for elt in a:
        print(elt)


def func1():
    a = Collection([1, 2, 4])
    for elt in a:
        print(elt)

    a[1] = 53
    for elt in a:
        print(elt)

class Collection:
    # ...

    def __contains__(self, items):
        self.items = items

    # ...
        
    def __setitem__(self, index, value):
        self.items[index] = value

    def __getitem__(self, index):
        return self.items[index]

    def __len__(self):
        return len(self.items)

```

**Comment by FabienArcellier** [comment]
Thanks @mmikita95 

Even if I am confident working arround list or tuple, I am not about working around datastructure as numpy or dataframe to move upward the mutation. 

That's the reason why I change my mind and would advocate to handle explicit mutation declaration in this sort of scenario.

**Comment by mmikita95** [comment]
Had a quick glance at what is happening, and here we have the case that `StateProxy`'s `__setitem__` at [core.py:210](https://github.com/streamsync-cloud/streamsync/blob/44afe030b941c11cc5eb42cc491d7b9acf87a5d2/src/streamsync/core.py#L210) is setting the whole `data` list at once (`else: value = raw_value`), and its contained `dict` objects are not converted to `StateProxy` instances and therefore can't track their mutations, which leads to this issue. Regarding the first option that @FabienArcellier proposed [here](https://github.com/streamsync-cloud/streamsync/issues/226#issuecomment-1927216304) – I'm afraid this wouldn't be a sufficient solution, as we'll effectively come to a need to have to handle every collection and custom class.

---

@FabienArcellier yeah, I agree that we might struggle with reliably (and quickly) processing mutations in deeply-nested data structures. But, to be honest, forcing user to declare mutations explicitly kind of feels like a reluctance to tackle this, opting for a simple "out-of-sight-out-of-mind" solution? I don't know for sure about this. One thing I'm certain about though is that this issue has very significant "architectural" implications, and the solution should be very future-proof.

I'll be looking into this on my side to better understand the scope of the problem and to try some potential solutions. Also, I think it'll be a good idea to schedule a meeting for us to discuss this in greater depth personally, and share ideas.
