### ISSUE TITLE
Flesh out component documentation 

### ISSUE THREAD

**Issue by knowsuchagency** [streamsync-cloud/streamsync#25]
This is such a brilliant project; thank you for creating it!

It might help adoption for the [component](https://www.streamsync.cloud/component-list.html) documentation to look more similar to that of [streamlit](https://docs.streamlit.io/library/api-reference).

I know the page says

```
Streamsync Builder displays this data in context, when selecting a component.

This page mainly intended towards those exploring the framework before installing it.
```

and that the best way to explore components is to run the builder, but it's more likely users would start using streamsync if they could immediately visualize the project's value.

**Comment by ramedina86** [comment]
Thank you! I've been checking the logs and it looks like "component list" is amongst the most visited pages, even though it's not prominently displayed. So it's definitely worth improving. Thank you for bringing attention to this, I'll leave this open.

**Comment by ramedina86** [comment]
I've published an improved version of the [component list](https://www.streamsync.cloud/component-list.html). Thanks again for the suggestion.
