### ISSUE TITLE
Binding don't seem work inside a repeater

### ISSUE THREAD

**Issue by AsafMah** [streamsync-cloud/streamsync#26]
![image](https://github.com/ramedina86/streamsync/assets/6424271/7b0fa425-a2a9-4a31-8160-0f3d783e6079)

(Two way binding like inputs)

It seems that it doesn't differentiate them.

**Comment by ramedina86** [comment]
The documentation should be clearer, thanks for reporting this. This is expected behaviour though, as you cannot bind to context, only to state.

You can create an event handler using state and context to achieve this. There's an example [here](https://www.streamsync.cloud/repeater.html) at the bottom

Thank you for trying Streamsync and providing feedback. Let me know if I can help.

**Comment by Capsar** [comment]
Best @ramedina86,

How does this work using a slider inside a repeater?

Binding does not work as you mentioned above, so how would a default value be set?

This is my handler function and it works:
```python
def handle_set_chunk_size(state, context, payload):
    name = context["itemId"]
    state["loaded_documents"][name]["chunk_size"] = payload
```

But when initializing the repeater the slider has no value:
![image](https://github.com/streamsync-cloud/streamsync/assets/10345197/c6184a06-9bdf-4aa3-8411-d237428025ae)

Binding it directly to for instance `item.chunk_size` seems more intuitive to me (no need to create such a event handler & can set default initial value).

Kind regards,
Caspar

**Comment by ramedina86** [comment]
Hey Caspar, this is a great point -thanks for bringing it to my attention.

I'll reopen the issue. It'll be quite challenging to implement this, but worth it.

**Comment by Capsar** [comment]
Hey Ramiro,

Has a fix for this been implemented already? Or a temporary work around that you can think of?

Best regards,
Caspar

**Comment by ramedina86** [comment]
Hi @Capsar not yet, though it hasn't been forgotten, it'll be implemented before the end of month.

**Comment by ramedina86** [comment]
Hi @Capsar it's now possible (v0.2.8) to bind inside a _Repeater_ using dynamic accessors, providing the functionality you detected was missing and some more.

For example, `persons[itemId].height` where `itemId` is the one generated by the _Repeater_.

This also gives you the chance to use `itemId` to point to a completely different dict. Although this was inspired by this issue specifically, it works outside _Repeater_ as well.

**Comment by thondeboer** [comment]
How is this supposed to work? Is this JSUT for the binding of components to items in the repeated items.

 Using your example from the docs (hint...you may want to update the docs for this use)

articles[itemId].colour 

Could be bound to some dropdownselect or some other input, so a user could SET the colour to some value and it will be updated in the state for "articles"?

For display we still use

```@{itemId.colour}```

Could be somewhat confusing to use two separate notations, but I guess the point for this is that now you could do something like

otherstate[itemId].someattribute

and set an attribute in some other state item, here now "otherstate".


```
ss.init_state({
    "articles": {
        "Banana": {
            "type": "fruit",
            "colour": "yellow"
        },
        "Lettuce": {
            "type": "vegetable",
            "colour": "green"
        },
        "Spinach": {
            "type": "vegetable",
            "colour": "green"
        }
    },
    "order_list": []
})
```
