### ISSUE TITLE
declare optional schema on streamsync state

### ISSUE THREAD

**Issue by FabienArcellier** [streamsync-cloud/streamsync#277]
The schema offer a way to associate a streamsync state with an explicit schema. The developer can specify how the state he builds in streamsync is structured.

This parameter is optional. If it is not provided, the current behavior which consists of interpreting dictionaries as substates is preserved.

This mechanism may solve 2 problems:

* specifies the type and allows plotly or vegas payloads not to be interpreted as a state (https://github.com/streamsync-cloud/streamsync/issues/226)
* offer autocompletion and type checking

# Simple example

```python
import streamsync as ss

class AppSchema(ss.StreamsyncState):
    counter: int

initial_state = ss.init_state({
    "counter": 0
}, schema=AppSchema)

# Event handler
# It receives the session state as an argument and mutates it
def increment(state: AppSchema):
    state.counter += 1
```

**Comment by ramedina86** [comment]
Shipped in 0.4.0. Thanks @FabienArcellier !
