### ISSUE TITLE
Implement pylint

### ISSUE THREAD

**Issue by ramedina86** [streamsync-cloud/streamsync#281]
Enforce quote consistency, etc

**Comment by FabienArcellier** [comment]
pylint is really slow to run in continuous integration. It was a pain in several on my past project when the codebase grow. I would be interested to give a try to [ruff](https://github.com/astral-sh/ruff) if we can enforce this rule.

**Comment by ramedina86** [comment]
Thanks for your input 🙏🏻
Let's explore that one then! Beyond quotes which is a minor thing I'm sure we can benefit from a linter. We certainly do in JS.

**Comment by mmikita95** [comment]
What do you guys think about [black](https://github.com/psf/black) – I believe it fits our use case, and feels more like an "industry standard", being used by big players?

**Comment by ramedina86** [comment]
[Seems like](https://astral.sh/blog/the-ruff-formatter) ruff is faster and can provide a "black-style" formatting if needed

**Comment by FabienArcellier** [comment]
black is a formatter, not a linter. It's primary goal is to modify files, not checking them. It's something mature. It's complementary to a linter.

It requires to plug in [git precommit](https://pypi.org/project/pre-commit) to make it confortable to use.

**Comment by FabienArcellier** [comment]
implement in https://github.com/streamsync-cloud/streamsync/pull/371
