### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by AmgadHasan** [streamsync-cloud/streamsync#31]
I tried to install it using conda anc conda package but the package cannot be found. Please make it available there

Thank you for creating this awesome package!

**Comment by ramedina86** [comment]
Thanks for the kind words and for your interest in this package. I'll do some research to better understand what's required to publish on Conda.

**Comment by martinmarroyo** [comment]
Hello, I'd like to work on this issue if it is still available to work on.

**Comment by ramedina86** [comment]
Hi @martinmarroyo yes help is still wanted on this one and it'd certainly be appreciated!

I'm mainly trying to understand what the requirements are and if all dependencies are available on Conda. I'm not familiar with Conda (I've never used it) so I find it quite challenging to get started with this as a non-user.

**Comment by martinmarroyo** [comment]
Hi @ramedina86 sounds good! I can go ahead and gather the requirements, run through a local implementation on my fork, and share notes + update if that works for you. Looking forward to working on this.

**Comment by ramedina86** [comment]
Hi @martinmarroyo , let me know when you have any updates on this, thanks!

**Comment by ramedina86** [comment]
Hi, closing this as using the package from PyPi via Conda seems to be working ok.
