### ISSUE TITLE
on edit mode when I am on a page generated in low code and the code is run again, the page become blank

### ISSUE THREAD

**Issue by FabienArcellier** [streamsync-cloud/streamsync#314]
I run the code, the edit page become blank, I have to click on the page again to see my change.

![Peek 2024-03-16 08-17](https://github.com/streamsync-cloud/streamsync/assets/159559/c6cd4ed8-ee2c-4c5b-827d-494f39af43db)

---
There is a workaround. If I set an identifier to the page, it is working well.

![Peek 2024-03-16 08-18](https://github.com/streamsync-cloud/streamsync/assets/159559/d5697420-ccd4-4956-a921-8f615bae21e2)

**Comment by mmikita95** [comment]
Solved in #328, with predefined IDs created for pages that are missing it
