### ISSUE TITLE
Code editor for full app

### ISSUE THREAD

**Issue by Wazarr94** [streamsync-cloud/streamsync#38]
While the visual editor is fantastic, I find that I prefer doing it both the backend and the frontend on my code editor.

From your [first article about Streamsync](https://medium.com/@ramiromedina/like-streamlit-but-fast-enabling-low-latency-data-apps-948b95b098a2), I can see that this was the initial way you chose. However, you went with the visual editor. Maybe there are drawbacks to the first approach, would really like to have your input.

If not, do you plan on having this interface back? Thanks

**Comment by Wazarr94** [comment]
The big issue that I didn't mention on the first post is making that we can't really have the visual and code approaches at the same time.

Maybe it is possible to put the frontend code in ui.py, and if this file is detected, then disable the possibility to use the visual editor? And there could be an option to use visual or code when creating the app as well.

**Comment by ramedina86** [comment]
This is a great question and it's made me think quite a bit.

As a general guideline on what to expect from Streamsync, I'm trying really hard to encourage best practices with minimum effort. It's of course an ongoing effort and there's a lot yet to be done.

The visual editor is that it enables separation of concerns in a rather intuitive way and lowers reliance on documentation.

Separation of concerns can of course be achieved with code, but it becomes harder to manage and it requires a lot of discipline to keep the code clean. Plus, you'd need to remember/check each of the properties for all components. I didn't even remember that _Column_ had an option named `isSticky`, so I don't think others would.

This would be rather straightforward to implement, but building a whole application like this I think would be a pain.

```py
with ssc.columns():
  with ssc.column({"width": "1", "isSticky": "yes"})
    ssc.text({"text": "Hello"})
  ssc.column({"width": "1", "title": "@{my_column_name}"})
    ssc.text({"text": "World"})
```

However, I'll probably experiment with it at some point, as I think it could work as a complement to `ui.json`. You could have "static" components (in `ui.json`) and "dynamic" components (rendered on-the-fly via Python calls).
