### ISSUE TITLE
Create a demo for LLMs.

### ISSUE THREAD

**Issue by AmgadHasan** [streamsync-cloud/streamsync#53]
Hi again.

LLMs are the craze now. I think if someone can create a clean and simple ui for chatting with LLMs and make a tutorial and post the tutorial on the docs, this will make this project much more popular.

Maybe something like oobaboga text gen web ui but simpler and cleaner?

I can help with this but I have little knowlege of front end stuff, I can help with the backend (setting up the model as an api call, etc)

Let me know if someone is willing to cooperate.

**Comment by ramedina86** [comment]
Hi Amgad, I thought of this too. I believe a need "Chat" component is required. Something can be built using the _Repeater_ component but I don't think it'd end up looking very elegant. I'll add building a _Chat_ component to the roadmap.
