### ISSUE TITLE
Is this project going to remain active in the foreseeable future?

### ISSUE THREAD

**Issue by AyushExel** [streamsync-cloud/streamsync#54]
Hey guys. thanks for the amazing project. I'm working on a project and I don't like some things about streamlit so I was thinking of moving to this. I just wanted to confirm if this project will be actively developed and maintained before starting to develop using this. Thanks!

**Comment by ramedina86** [comment]
Hi Ayush, thank you! Yes, the project will remain active for the foreseeable future and several new features are in the pipeline.
