### ISSUE TITLE
Support for keyboard/mouse events

### ISSUE THREAD

**Issue by darren-harton** [streamsync-cloud/streamsync#55]
Hi, just wanted to see if this something you would consider supporting. 

My use case is that I wanted to use Streamsync to build a tool kit for managing datasets. Keyboard events, such as using arrow keys or the scroll wheel to move through entries, would make this much more usable.

Thanks!

**Comment by ramedina86** [comment]
Hi Darren, thanks for suggesting this.

In the next release, events will have a big upgrade. I'll make sure to support keyboard events.
