### ISSUE TITLE
Couple of questions / features in creating a LLM Application

### ISSUE THREAD

**Issue by Capsar** [streamsync-cloud/streamsync#57]
Hi,

I am seriously enjoying your library while creating an application together with the python package for LangChain; currently focussing on analysing documents by uploading a batch of PDFs and then processing them.
Goals are creating quick scientific paper reviews, and smartly searching through a batch of scientific papers.

I have the following questions:
- Rendering a PDF in a HTML Element following [https://stackoverflow.com/questions/17784037/how-to-display-pdf-file-in-html](https://stackoverflow.com/questions/17784037/how-to-display-pdf-file-in-html) does not seem to work yet. A separate element for this would be wonderful.
- I have the issue where a dropdown element is larger than the sidebar, I cannot seem to figure out how to set the width for either component.
- Having a way to copy text to clipboard (then I can create a view plane with Markdown text + a copy to clipboard button)
- How do I update a state before the end of a function is reached? aka set state variable to "loading...." then call load function and when finished set variable to "loaded"

Again, I am seriously enjoying the library and I find it very intuitive to use 👍 

Best regards,
Caspar

**Comment by nicolalandro** [comment]
In [that app](https://gitlab.com/nicolalandro/study-streamsync/-/tree/main/pdf_input_app) I made an example for how to show pdf and I'm working do copy to clipboard

![immagine](https://github.com/streamsync-cloud/streamsync/assets/18419702/80633bd2-56a0-47d4-b59b-a79bc32400c7)

**Comment by nicolalandro** [comment]
![immagine](https://github.com/streamsync-cloud/streamsync/assets/18419702/dc8d72d3-6fc1-46f0-995f-07f87889c827)
Now I also create a Copy To Clipboard button by setting an HTMLElement with onclick that is generated each time you modify the text, that button do `navigator.clipboard.writeText("{base_text.encode("unicode_escape").decode("utf-8")}")`

**Comment by Capsar** [comment]
Hi @nicolalandro,

Thank you! I got both of your methods to work in my application. Unfortunately it does not seem like we can add event listeners to arbitrary HTML-Elements, so a notification when the text is copied to the clipboard is not easily done yet.

Best regards,
Caspar

**Comment by gaturchenko** [comment]
Hey @Capsar +1 on the "loading..." question, would be great to find out how to achieve this functionality.

**Comment by ramedina86** [comment]
Hi @Capsar , apologies, I missed this issue report and only realised after the last message. I'm glad you like the library, I hope you're still exploring it.

- PDF should be fine, as @nicolalandro was showing. There might be something else at play in your case, like HTTP headers, see #56 
- Regarding width of _Dropdown Input_... my bad, thanks for reporting. I was able to reproduce this and I'll fix it.
- I don't think this will be natively supported soon but you can now write custom JS and call it from the backend to achieve this.
-  State updates during long-running calls i.e. "Loading..." will be supported in the next version, please see #82
