### ISSUE TITLE
Change max file upload size?

### ISSUE THREAD

**Issue by ruckc** [streamsync-cloud/streamsync#58]
I'd like the ability to change the max file upload size.  It appears its hardcoded in [CoreFileUpload.vue](https://github.com/streamsync-cloud/streamsync/blob/5decf9966b65b4561c87da34b8e03d140ce84889/ui/src/core_components/input/CoreFileInput.vue#L21).

**Comment by nicolalandro** [comment]
The problem still remain? https://github.com/writer/writer-framework/blob/dev/src/ui/src/core_components/input/CoreFileInput.vue#L35
