### ISSUE TITLE
You can add "root" to the tree structure of the "page". It looks like a bug

### ISSUE THREAD

**Issue by s4k17** [streamsync-cloud/streamsync#59]
I understand that this is more of a typo in the code than a full-fledged bug, but I decided that it should be noticed. 
![image](https://github.com/streamsync-cloud/streamsync/assets/24322601/24cd93f8-bec0-4a77-9d95-f6c5a7a498e0)

Overall, I really like the idea and architecture of **streamsync**. I think it will be a very powerful tool in the future and it already looks very cool!

I always wanted such a tool for my work and projects, and I will try to participate in the development and testing

**Comment by ramedina86** [comment]
Hi @s4k17 , thanks for bringing this to my attention. I'm glad you like Streamsync!

Can you please tell me how you arrived to this result? Was it through a standard way (e.g. drag and drop, copy and paste) or via editing the file?

If you arrived to this via a standard way I'd definitely consider a bug. If not, I probably wouldn't, but still would like to know and likely issue a warning.

**Comment by ramedina86** [comment]
Fixed in v0.1.12, which was just released.
