### ISSUE TITLE
How to use State from custom Web Component or JS?

### ISSUE THREAD

**Issue by nicolalandro** [streamsync-cloud/streamsync#61]
I'm trying to include [SeqViz](https://github.com/Lattice-Automation/seqviz) component into my project [here the source code](https://gitlab.com/nicolalandro/study-streamsync/-/tree/main/custom_component_app?ref_type=heads).

![immagine](https://github.com/streamsync-cloud/streamsync/assets/18419702/5bdc5ebc-ba6f-4349-ad70-6df7d8012cef)

The question is: how can I interact with the state from custom JS?

## My solution
I create an HTML element of type script with the src of the component, after another HTML of type DIV with the variables into attr, and after another HTML element of type script that load static js that read variables from attr with following code:

```
setTimeout(function () {
    console.log("Readed: " + core.getComponentById("c79e92e2-ce45-4532-849f-704391de6224").content.attrs)
    var attrs = JSON.parse(core.getComponentById("c79e92e2-ce45-4532-849f-704391de6224").content.attrs)

    window.seqviz
        .Viewer("seqviz", {
            name: attrs.name,
            seq: attrs.seq,
            style: { height: "50vh", width: "100%" },
            annotations: [{ name: "promoter", start: 0, end: 34, direction: 1 }],
            highlights: [{ start: 0, end: 10 }],
            enzymes: ['Q']
        })
        .render();
}, 500);
```
## Problems
* the timeout seams necessary during the `streramsyc run` but not during the `streamsync edit` probably because the js is just loaded when I click preview
* It read correctly the attrs if I put it directly but If I use a variable like @{dna} that I define In my python code I read '@{dna}' from that variable and not the value from the state.
* I do not have idea about how to change some state variable or stimulate event to the python

So how can I resolve that situation?

**Comment by nicolalandro** [comment]
Perfect! I solved It. Instead for call some funcion how can I do?

**Comment by ramedina86** [comment]
Awesome! Regarding functions...

- Frontend function. In the latest release, v0.1.12 it's possible to import an ES6 module and trigger a function from the backend. 
- Backend function. To trigger a backend function you'd need to fire an event and have a valid event handler. Right now there's no support for custom events, which is probably what you're after. It's coming in the next version together with custom components.
