### ISSUE TITLE
X,y of click event in Image component

### ISSUE THREAD

**Issue by lincoln2491** [streamsync-cloud/streamsync#66]
Hi

Thanks for the fantastic work. I really like this tool, but I have one suggestion about features, the ability to read the xy coordinates of a click event on the image component would be useful. Maybe should be passed to function by context parameter.

**Comment by ramedina86** [comment]
Hi, thanks for the kind words. I'm glad you're enjoying Streamsync. Events will soon get a big upgrade; this will be supported in the next release.

**Comment by lincoln2491** [comment]
Hi

Thanks for letting me know. I will be waiting.

**Comment by ramedina86** [comment]
Happy to hear that, thanks for your patience!
