### ISSUE TITLE
Docker image does not run on local Macbook M1 Pro

### ISSUE THREAD

**Issue by gaviriar** [streamsync-cloud/streamsync#69]
I am having some issues running the docker container for the `hello` app. Would appreciate some help, maybe you can try to reproduce it? 

**Steps to Reproduce**

1. Create the `hello` app
2. Build the hello docker image `docker build -t streamsync-hello:local .`
3. Run the image locally `docker run -p 5000:5000 streamsync-hello:local`

**Observations**

1. Nothing is printed out in the console after the docker image has been run
2. When accessing https://localhost:5000, no data is loaded, and there are error notifications
<img width="1792" alt="image" src="https://github.com/streamsync-cloud/streamsync/assets/2001662/2dbd759f-c676-42c1-ad47-850cbbd475cb">

**Environment**
MacBook Pro 
Chip: Apple M1 Pro
OS: macOS Monterey

**Comment by ramedina86** [comment]
Hi, thanks for reporting this.

Please change the pip line in the Dockerfile to

`RUN pip3 install 'streamsync[ds]' && pip3 install -r requirements.txt`

in order to install `streamsync[ds]` with the data science dependencies for hello. That should fix it, please let me know if it doesn't.

Alternatively you can edit `requirements.txt` to add the optional dependencies manually. I'll classify this as a bug given that since the Dockerfile is in the hello app, it really makes you think that it should work as-is for the hello app.

**Comment by gaviriar** [comment]
@ramedina86 thanks for the quick response. That seems to be resolving the issue for the `hello` app. It does not seem to work for my local app, and likely due to missing dependencies. 

The challenge is that when I run the container, there is not output on stdout or stderror so I cannot figure out what is wrong, do you have any tips for debugging? Is there a debug flag I could use to print the output?

**Comment by gaviriar** [comment]
> for

Ok, another update. The `main.py` failed to run due to a missing file that is not in the Docker image. But to find that out I had to `docker run -it <containerhash> sh` and then run the `python main.py` to actually see the error and stack trace which I don't see when I run the container.

**Comment by gaviriar** [comment]
> @ramedina86 thanks for the quick response. That seems to be resolving the issue for the `hello` app. It does not seem to work for my local app, and likely due to missing dependencies.
> 
> The challenge is that when I run the container, there is not output on stdout or stderror so I cannot figure out what is wrong, do you have any tips for debugging? Is there a debug flag I could use to print the output?

Ok, another update. The main.py failed to run due to a missing file that is not in the Docker image. But to find that out I had to docker run -it <containerhash> sh and then run the python main.py to actually see the error and stack trace which I don't see when I run the container.

**Comment by ramedina86** [comment]
Apologies for the delay on this, in v0.2.7 it's now possible to see the error directly without having to access Builder, as logs are streamed to the terminal.
