### ISSUE TITLE
DataFrame Object Wont Display Last Row

### ISSUE THREAD

**Issue by WilliamJudge94** [streamsync-cloud/streamsync#71]
**Issue:**

In main.py, when creating a pandas DataFrame and displaying it inside Streamsync, the last row is typically cut off from the display. I'm currently appending a blank row at the end of the DataFrame to display everything properly, but it would be more efficient not to have to do this workaround.

**Steamsync Version:** 1.10

**Steps to Reproduce:**

Create a pandas DataFrame in main.py.
Display the DataFrame in Streamsync.
Observe that the last row is missing from the display.
Expected Behavior:
All rows of the DataFrame should be displayed without the need to append a blank row.

**Actual Behavior:**
The last row of the DataFrame is cut off from the display.

**Comment by ramedina86** [comment]
Hi William, thanks for reporting.

I haven't experienced this in the tests I've done and I'd be really interested in reproducing it. Can you please share which browser you're using?

Also, have you tried the latest version? Even though I didn't experience the bug, I did notice that the CSS code didn't account for the header row, considered this potentially problematic, and made a change for 0.1.12.

![image](https://github.com/streamsync-cloud/streamsync/assets/64783088/4d43be9d-b65b-4247-b754-cb3c6ed4b111)

Just saw the sponsorship by the way, thanks a lot!

**Comment by ramedina86** [comment]
Closing this issue as I believe this should be fixed, feel free to reach out if you're still experiencing a problem.

**Comment by WilliamJudge94** [comment]
I realized that some of my code still required Pydantic V1. I have been trying to update some code for V2, but has been taking a bit to update. Sorry for the late reply. 

Also you are welcome! This is an amazing project!
