### ISSUE TITLE
How to add navigation to sidebar

### ISSUE THREAD

**Issue by maziggy** [streamsync-cloud/streamsync#72]
Cannot figure out how to add a page menu to the sidebar. Do I have to use a HTML element?

Thank you!

**Comment by ramedina86** [comment]
Hi, what kind of menu do you have in mind?

If for example you just want to switch between pages when a _Text_ component is clicked, you can easily do so. 

You will need to assign keys to the pages to make sure they can be navigated to. More info on [Page routes](https://www.streamsync.cloud/page-routes.html) docs.
