### ISSUE TITLE
Cannot drag and drop

### ISSUE THREAD

**Issue by mopi21** [streamsync-cloud/streamsync#75]
I tried dragging in an image or a textfield in the page but after dropping it, it does not appear on the page. I have it running on and azure server and call in via --enable-remote-edit in case that makes a difference.

**Comment by ramedina86** [comment]
I haven't heard that before, so I'm not sure. 

Do you mind sharing if there are any errors in your browser console?

If it's a public app please share the URL and I can take a look

**Comment by mopi21** [comment]
There is no error, if I drag and drop it, it just does not show up in the middle ! happy to show you via shared screen if you are interested

**Comment by ramedina86** [comment]
I looked into your case in more detail. I believe what's going on is that you're not using Builder in a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts). Basically, either in localhost or in a https website.

Some web APIs that are required are only available in a secure context. Unfortunately, Builder fails silently so this is something that need to be fixed, displaying a message like "You should use a secure context".

If this isn't the case, please let me know and I'd be happy to look at your screen, thanks for the offer!
