### ISSUE TITLE
Selectbox and Multiselect Inputs

### ISSUE THREAD

**Issue by TPreece101** [streamsync-cloud/streamsync#76]
Some things that I do miss from Streamlit when I'm using this library are the Selectbox and Multiselect widgets. Particularly the ability to type what you're looking for and easily select it.

Is there any scope for including some similar widgets in Streamsync?

I'm wondering if you've considered using any component libraries to help you with this project? For example the Quasar library has many Vue components with lots of options that _might_ be easy to integrate into Streamsync. For example the select component with autocomplete could be a good substitute for the Selectbox: https://quasar.dev/vue-components/select#filtering-and-autocomplete

Let me know what you think 😊

**Comment by ramedina86** [comment]
I agree that Streamlit has great form components.

It's a short term goal to raise the standard of Streamsync's form components to rival Streamlit's. That includes improving existing ones but also adding others like multiselect and range slider.

I don't plan on using component libraries. I consider this a core part of the project. I plan to walk the hard, Streamlit-like path on this, as opposed to NiceGUI (who used Quasar). Certainly there are benefits to both!

**Comment by ramedina86** [comment]
Hi, _Select Input_ and _Multiselect Input_ are available on 0.2.6.

https://github.com/streamsync-cloud/streamsync/assets/64783088/95e61ff0-5b63-42ee-824d-a948cba6e938

There's a still a lot of work to do (range slider, improving file upload, etc) but this is the first step towards better form components.

**Comment by TPreece101** [comment]
These look great, thanks for your work on these @ramedina86 😊
