### ISSUE TITLE
How to change the state first while executing an input field callback?

### ISSUE THREAD

**Issue by gaturchenko** [streamsync-cloud/streamsync#82]
Hi! Below is the UI of my app:
<img width="1168" alt="image" src="https://github.com/streamsync-cloud/streamsync/assets/70841338/1d40ce8b-5e1b-4637-a5d6-17ba132fc5dc">
I have a function which reacts to the "ss-file-change" event by processing the uploaded file. What I'm trying to achieve is to change the text of the message below when the file is uploaded and being processed, so that the user knows something's happening on the background. However, what I noticed is that my callback function would first execute any code not related to the state, and only then proceed with changing the state dictionary. Therefore, while I can inform the user that the file has been processed or there's been an error, I cannot indicate something's going on behind the hood. So my question is, is it possible to achieve the functionality I'm looking for? If yes, then how can I do it?

**Comment by ramedina86** [comment]
Hi, not possible right now, state mutations are all processed at the end of the call. But the next release (in about 2 weeks) periodically checks state during long-running calls. There'll also be a "loading" type of message with prefix "%".

I'll also fix _File Input_ to clearly show that a file is being uploaded. Right now the only indication of activity is the subtle green bar at the top.

![stateenquirydemo](https://github.com/streamsync-cloud/streamsync/assets/64783088/c818a1e3-8764-4e4e-810b-52448cc297e5)

```py
def handle_start_process(state):
    import time

    for i in range(10):
        state["short_text"] = "% Loading..." + str(i*10) + "%"
        time.sleep(0.5)

    state["short_text"] = "+Completed"
```
