### ISSUE TITLE
Production/Future ?

### ISSUE THREAD

**Issue by PasVegan** [streamsync-cloud/streamsync#86]
Hello,

I'm genuinely impressed with StreamSync and am considering it for developing an interactive dashboard for my company. Before I commit, I'd like to understand the long-term support plan for this library. Can you assure regular updates and consistent support? It's essential for us not to integrate tools that might become obsolete or unsupported in the near future.

Thank you.

**Comment by ramedina86** [comment]
Hello, I'm glad you're enjoying Streamsync. Yes, absolutely, the framework will keep on being updated.

It was released only 3 months ago and I consider the current version to be a "bare bones" one compared to where it'll be once it reaches maturity; I expect this to happen around April 2024. But I'm thrilled that many people are finding even v0.1 useful/exciting. In summary, stick around, not only it'll be updated, it'll get much better.
