### ISSUE TITLE
Plotly graph fullscreen

### ISSUE THREAD

**Issue by PasVegan** [streamsync-cloud/streamsync#87]
Hi,

How can I make a plotly graph take the whole screen on a page. Maybe you can add a way to modify that in the component properties in the future with the builder ?

**Comment by ramedina86** [comment]
Hi,

I believe this is a rather niche requirement given the type of application you're developing, so I don't think there'd much interest for the Builder feature (always ready to be proved wrong though).

Nevertheless, you can achieve this by putting the Plotly graph inside a _HTML Element_ that takes the whole screen, or using a custom CSS class to stretch the Plotly graph container.

The basic idea is something like:

```css
position: fixed;
left: 0;
top: 0;
width: 100vw;
height: 100vh;
```

**Comment by PasVegan** [comment]
How can I put a ploty graph inside a HTML Element ? I tried exporting to html and passing the buffer to a state reference in the Html Element Attributes. But it doesn't work
```
buffer = io.StringIO()
figure.write_html(buffer)
initial_state = ss.init_state({
    "html_plotly": buffer.getvalue(),
})
```



![image](https://github.com/streamsync-cloud/streamsync/assets/114608503/ae27d407-d9ca-444c-a2f5-3b3de39ff35a)

**Comment by PasVegan** [comment]
I found out that setting the height in `figure.update_layout(height=1080)` works but the autosize=True don't, it's supposed to the take the parent container size but it doesn't work here. How can i make the plotly chart take the whole size of the html element so that it adapt to different screen resolution ?

**Comment by ramedina86** [comment]
Hi, this weekend I'll release a new version that supports autosize better. Another way to get that behaviour would be to import a CSS that does this

```css
.CorePlotlyGraph {
	height: 100%;
}

.CorePlotlyGraph .target {
	height: 100%;
}
```

**Comment by PasVegan** [comment]
The autosize still doesn't work even with the new version, the width adapt correctly but the height stay the same.

For the CSS, do I put it in static/custom.css and pass the .CorePlotlyGraph class to the plotly graph and html with the builder ?

**Comment by PasVegan** [comment]
I found that when I remove the background in the html element style object the autosize doesn't work any more but it works with that:
```
{
  "height": "100vh",
  "width": "100vw",
  "background": "linear-gradient(90deg, rgba(41,207,0,1) 0%, rgba(145,231,78,1) 100%)"
}
```

**Comment by ramedina86** [comment]
Hi, it's probably the JSON structure rather than the background.

For example, if you have the following, it won't work because of the comma after the width definition.

```css
{
  "height": "100vh",
  "width": "100vw",
}```
