### ISSUE TITLE
Enable Asynchronous Execution of Python Functions with Timer Component

### ISSUE THREAD

**Issue by sarim-zafar** [streamsync-cloud/streamsync#89]
Hello,

I am thoroughly enjoying this library and appreciate how seamlessly it functions. Currently, I'm utilizing the timer component to perform a classification task on an entire dataset, updating a pie chart based on the results. However, I'm facing a concern regarding potential blocking of the application during this process.

I have implemented a use case where the timer component is employed to perform a classification task on a sizable dataset. As a result, the pie chart gets updated based on the classification results. While this works well, I'm concerned about the potential for blocking the application during the execution of this task.

Desired Feature:
I'm wondering if it would be possible to extend the functionality of the timer component to allow for the asynchronous execution of Python functions. This would enable my classification task to run in the background, ensuring that it doesn't block other essential processes or user interactions within the application.

Additional Information:
Any suggestions or best practices on how to achieve asynchronous execution within the current library would be greatly appreciated.

I'm open to discussing potential implementation ideas or strategies that could make this feature feasible.

Library Version: 0.1.12

**Comment by ramedina86** [comment]
Hello, I'm glad to hear you're enjoying this library and that it's working well for you.

I have good news, I've just released a new version which runs all event handlers asynchronously to better support long-running tasks. It seems to be perfectly in line with what you were requesting. There's also other new features targeting background/long-running tasks.

It seems like you're building something interesting by the way.

**Comment by sarim-zafar** [comment]
Yes I can see that however I can't seem to put some of the variables in the state dict as they are non serialisable (numpy arrays). What's the proposed way of tackling this issue as I want to avoid using global variables. Is there anyway I can send in other variables with events?

**Comment by ramedina86** [comment]
If you have something that you want to store in state but avoid serialising, you can prefix them with an underscore. [More info here](https://www.streamsync.cloud/application-state.html#backend-only-elements).

Numpy arrays are serialisable, however you may have something inside them that's preventing serialisation. For example, complex numbers.

Here's an example of a non-serialisable Numpy array that can be kept in state, but isn't serialised (nor send to the frontend).

```py
initial_state = ss.init_state({
    "_k": np.array([1+2j, 2, 3])
})

def print_k(state):
    print(state["_k"])
```

Hope this helps!
