### ISSUE TITLE
Q: How can I limit the number input boxes to some value?

### ISSUE THREAD

**Issue by thondeboer** [streamsync-cloud/streamsync#93]
I'm trying to limit the number input box to only allow numbers >=0 and have a simple event handler that does this, but it won't keep the value at 0 if I use the arrows in the box or enter a new value < 0.
```python
import streamsync as ss

# This is a placeholder to get you started or refresh your memory.
# Delete it or adapt it as necessary.
# Documentation is available at https://streamsync.cloud

# Shows in the log when the app starts
print("Hello world!")

initial_state = ss.init_state({
    "my_app": {
        "title": "RNAyx"
    },
    "comparison": "~ Genotype",
    "fdr_cutoff": 0.001,
    "minimal_base_mean": 0,
    "minimal_abs_lfc": 0,
    "k_means_groups": 2,
})

def generate_heatmap(state):
    print("We are generating the heatmap")

def check_minimal_base_mean(state, payload):
    state['minimal_base_mean'] = max(0, payload)
```

And I have defined the placeholder for the value as `@{minimal_base_mean}`

I also tried binding (in addition to the event handler) but it does not seem to work.
Is there a way to limit the input values and represent that in the UI as well...The state is actually never going below 0, but the UI does not get updated

**Comment by ramedina86** [comment]
This is a very reasonable requirement, thanks for sharing. I'll add min, max and step to the next release. In the meantime this can be solved using binding and the "change finish" event.

https://github.com/streamsync-cloud/streamsync/assets/64783088/ce397723-5eb1-40df-bcb3-cef5c05b2ba8
