### ISSUE TITLE
add state explorer

### ISSUE THREAD

**Issue by wgong** [streamsync-cloud/streamsync#94]
The layout explorer for UI elements is very powerful and intuitive, 
When going to property panel, for value and event handler, one has to mentally remember all the states defined in the code, and knows which is which.
It would be great to add a similar explorer for `state`.

**Comment by PasVegan** [comment]
It's already in the roadmap but i agree too !

**Comment by ramedina86** [comment]
That's right! Like @PasVegan mentioned it's already in the roadmap. Should really enhance the developer experience.

**Comment by wgong** [comment]
@ramedina86 what is link to roadmap?
