### ISSUE TITLE
add Help to top menu bar

### ISSUE THREAD

**Issue by wgong** [streamsync-cloud/streamsync#96]
Can you add a new item called "Help" which links to 

- GitHub source - https://github.com/streamsync-cloud/streamsync
- Documentation - https://www.streamsync.cloud/getting-started.html
- Community Forum ??
- Demo apps

I am not very familiar with the codebase yet, but willing to help with such simple feature enhancement

**Comment by SurajRaika** [comment]
are you talking about adding Help Button in Editor ?

**Comment by wgong** [comment]
Exactly

**Comment by ramedina86** [comment]
Hello, I'll consider adding this in the future
